# Dependencies
markdown:         kramdown
highlighter:      rogue

# Setup
title:            OpsBug
tagline:          'Strong Opinions, Weakly Held'
description:      'Tech Renissance'
url:              http://claraleung.github.io
baseurl:          

author:
  name:           'Vikram Dhillon'
  url:            https://twitter.com/opsbug

paginate:         3
